server:
  port: 8000

spring:
  application:
    # 应用名称
    name: oauth2-gateway-8000
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8880 #控制台地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #注册中心使用nacos
      config:
        server-addr: 127.0.0.1:8848 #配置中心使用nacos
        file-extension: yml #配置文件后缀
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lowerCaseServiceId: true
          #另一种写法
          #lower-case-service-id: true
      default-filters:
        - TokenRelay=
      #路由配置
      routes:
        - id: oauth2-server-9000
          uri: lb://oauth2-server-9000
          predicates:
            - Method=GET,POST
            - Path=/server/oauth/**
          filters:
            - StripPrefix=2
        # nacos中的服务1（每个服务中可集群多个应用，可在nacos中配置与治理）
        - id: oauth2-resource-a-8001
          uri: lb://oauth2-resource-a-8001
          predicates:
            - Method=GET,POST
            - Path=/server/a/**
          filters:
            - StripPrefix=2

  security:
    oauth2:
      client:
        registration:
          # 客户端：与注册时保持一致
          myClient:
            client-id: my_client
            client-secret: 123456
            #client-name: my_client_name
            scope: read,write
            authorization-grant-type: authorization_code
            provider: myOauth2
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          # 服务提供地址
          myOauth2:
            #issuer-uri: http://os.com:9000
            # issuer-uri 可以简化下面的配置
            # 请求授权码地址 获取code
            authorization-uri: http://os.com:9000/oauth2/authorize
            # 请求令牌地址
            token-uri: http://os.com:9000/oauth2/token
            # 用户资源地址
            user-info-uri: http://os.com:9000/oauth2/user
            # 用户资源返回中的一个属性名
            user-name-attribute: name
            user-info-authentication-method: GET

logging:
  level:
    org.springframework.cloud.gateway: debug
